### ISSUE TITLE
Tradução da imagem

### ISSUE THREAD

**Issue by alexandre-mbm** [OSMBrasil/semanario#30]
- [ ] Lembrar de incluir no script que popula GitHub com milestone

**Comment by vgeorge** [comment]
Tem a legenda embaixo e a imagem não é vetorial. Não vejo a necessidade de tradução.

**Comment by alexandre-mbm** [comment]
Se sobrar tempo e vontade, farei. Não é vetorial mas aparenta ter traços e fontes simples.
