### ISSUE TITLE
Organização mais direta

### ISSUE THREAD

**Issue by jgpacker** [OSMBrasil/semanario#31]
Olá, como geralmente vamos mexer num mesmo arquivo, penso que poderiamos utilizar um documento Etherpad (que é o "Google Docs open-source"), pra não precisarmos ficar lidando com conflitos. Continuariamos editando um texto markdown

Como o Etherpad tem colaboração em tempo real, nem precisariamos nos preocupar em estar traduzindo o mesmo que outras pessoas, pois só precisaria ver se os outros já traduziram aquilo ou não.

Quanto à organização da tradução, acho que basta ficar mencionando o pessoal no Slack#semanal e colocar comentários e/ou marcações no documento Etherpad em vez de organizar em _issues_ do Github.

**Comment by vgeorge** [comment]
Eu gosto do Github porque tudo tem histórico e fica centralizada a hospedagem dos arquivos fontes (.md) para serem usados no site da OSM Brasil e Mapas Livres.

**Comment by alexandre-mbm** [comment]
Isso que você está propondo com certeza funciona, na condição ideal em que todos estarão sempre com gás e sincronizados em suas vontades. Porém, o GitHub deixa uma organização mais rígida, menos vulnerável às falhas humanas (preguiças, afastamentos ou mesmo gulas). Eu acho melhor o caminho do GitHub como uma forma de deixar o processo mais "frio", independente de humores.

**Comment by jgpacker** [comment]
Não compreendo como uma organização mais rígida (i.e. mais trabalhosa) ajuda.

Se o objetivo é para fazer posts espelho em outros sites, então poderíamos sempre colocar no repositório as traduções quando prontas (podendo ainda revisar). Mas as traduções da última edição deveriam ser feitas no Etherpad, devido à maior facilidade de colaboração e auto-organização.
O Etherpad também possui um histórico, embora não seja tão fácil ver quem mexou na linha XYZ quanto no github.

**Comment by alexandre-mbm** [comment]
Essa organização que quero propor e o ensaio está em curso, não seria tão mais trabalhosa, porque seria toda estruturada por um script.

Este repositório não tem objetivo de fazer espelho, apenas de organizar um fluxo de trablho. Se conseguirmos conversar essa do espelho sem rejeição determinante vinda da equipe do weeklyOSM, os resultados finais alcançados aqui seriam copiados em posts no osmbrasil.github.io.

Kanban é muito prático e organizado. Por favor, leia meu comentário-resposta à issue #32.

**Comment by alexandre-mbm** [comment]
Realmente. Dou o braço a torcer. A diferença de agilidade é gritante! Não encontraremos nada mais direto do que isso: http://pad-osmbrasil.rhcloud.com/p/WeeklyOSM-257

A não ser que acontecessem mudanças no fluxo de trabalho (ferramentas) da equipe internacional; mas isso está fora de cogitação. Enterremos o assunto.
