### ISSUE TITLE
Usar pull requests

### ISSUE THREAD

**Issue by vgeorge** [OSMBrasil/semanario#32]
Foram criadas diversas tarefas de revisão, o que vejo como desnecessário. Se usarmos pull request para nossas edições, já teríamos este controle de quem fez o quê e a oportunidade de revisar com base no que foi enviado.

**Comment by alexandre-mbm** [comment]
A falha que eu vi com os pull requests **sozinhos** foi que eles não podem ser editados para aceitação. Primeiro eles são aceitos, para só depois receberem commits de alteração em cima. Ou seja, a leitura para a aceitação de um pull request não é exatamente uma revisão.

Mas OK. Eu começo a ver que usarmos pull requests pode ser útil, **sem excluir a criação das tais issues de revisão**. Por favor, experimente ou emule o seguinte:
1. Você recebe um pull request e abre a aba "arquivos alterados" para ler
2. Você está com o kanban aberto e move para `ready` as issues de revisão contempladas por aquele pull request
3. Enquanto você lê uma seção, move a issue correspondente para `in progress`
4. Caso alterações sejam necessárias, a issue está em `in progress` enquanto você edita localmente e não comita
5. Quando você comita e com isso conclui a revisão, você move o cartão da issue para `done` e ela é fechada

Não veem vantagem nessa metodologia?

---

PS.: chamando o @jgpacker 

---

![captura de tela de 2015-06-26 15-31-57](https://cloud.githubusercontent.com/assets/957501/8384601/7270f08e-1c18-11e5-9f4e-67840d5873e6.png)

**Comment by alexandre-mbm** [comment]
A primeira versão do [paicemana](/OSMBrasil/paicemana), que provavelmente será usada ainda ao menos com o milestone 257, realmente cria "uma ruma de issues". Se o documento markdown tiver 11 seções, no milestone serão pelos menos 22 issues, metade de tradução e metade de revisão.

**Mas não se preocupem!** Estruturas de dados que já existem no paicemana vão possibilitar fáceis customizações no sentido de diminuir a quantidade de issues. Por exemplo, numa versão 2, o paicemana poderá estar gerando apenas uma issue por colaborador, totalizando três issues no milestone, cada issue contendo duas listas de tópicos: uma gerenciando traduções e outra gerenciando revisões.

PS.: chamando o @jgpacker, já que ele não acompanha esta issue.

**Comment by alexandre-mbm** [comment]
Como combinado, o fluxo de trabalho será outro: http://pad-osmbrasil.rhcloud.com/p/WeeklyOSM-257
